// Generated by scripts/import-supplier-products.mjs. Review before merging into src/data/products.ts.
// Do not expose supplierCostEstimate, supplierName or supplierUrl in public UI.
import type { InternalProduct } from '@/data/products';

export const importedSupplierProducts = [
  {
    "slug": "sample-waterproof-seat-cover",
    "id": "sample-waterproof-seat-cover",
    "name": "Sample Waterproof Seat Cover",
    "price": 549,
    "compareAtPrice": 699,
    "category": "Car Protection",
    "categorySlug": "car-protection",
    "categoryName": "Car Protection",
    "subcategory": "Car Protection",
    "image": "/products/dog-seat-cover.svg",
    "gallery": [
      "/products/dog-seat-cover.svg",
      "/products/dog-seat-cover.svg",
      "/products/dog-seat-cover.svg"
    ],
    "galleryImages": [
      "/products/dog-seat-cover.svg",
      "/products/dog-seat-cover.svg",
      "/products/dog-seat-cover.svg"
    ],
    "shortDescription": "Water-resistant back-seat protection for dog hair and muddy paws.",
    "fullDescription": "A practical seat cover sample entry for supplier import testing. Replace this row with a real supplier-approved product before launch.",
    "benefits": [
      "Protects seats",
      "Easier cleanup",
      "Useful for road trips"
    ],
    "features": [
      "Water-resistant surface",
      "Headrest straps",
      "Wipe-clean finish"
    ],
    "bestFor": [
      "Dog hair",
      "Muddy paws",
      "Back-seat travel"
    ],
    "notIdealFor": [
      "Products without confirmed supplier specifications.",
      "Customers who need guaranteed fit before measurements are checked."
    ],
    "qualityNotes": [
      "Imported supplier product. Confirm specifications, samples and photo permission before setting launchVisible to true.",
      "Check material, stitching, fasteners and packaging before launch."
    ],
    "material": "Quilted polyester specification to confirm",
    "dimensions": [
      "Universal rear seat fit to confirm",
      "Measure before ordering"
    ],
    "measurements": [
      "Universal rear seat fit to confirm",
      "Measure before ordering"
    ],
    "compatibility": [
      "Confirm fit against supplier measurements before launch."
    ],
    "whatsIncluded": [
      "Sample Waterproof Seat Cover"
    ],
    "howToUse": [
      "Confirm usage instructions with the supplier before publishing.",
      "Add practical PawTrip SA usage notes after sample testing."
    ],
    "careInstructions": [
      "Confirm care instructions with the supplier before publishing."
    ],
    "deliveryNote": "Delivery estimates depend on product availability and customer location.",
    "returnNote": "Unused items can be returned in line with our returns policy.",
    "seoTitle": "Sample Dog Car Seat Cover South Africa | PawTrip SA",
    "seoDescription": "Sample imported product for PawTrip SA supplier workflow testing.",
    "tags": [
      "Car Protection",
      "Dog hair",
      "Muddy paws",
      "Back-seat travel"
    ],
    "isBundle": false,
    "relatedProductSlugs": [],
    "sourcePermissionStatus": "original_photos_needed",
    "availability": "checking_availability",
    "shippingClass": "standard",
    "imageReady": true,
    "launchVisible": false,
    "problemsSolved": [
      "Protects seats",
      "Easier cleanup",
      "Useful for road trips"
    ],
    "faqs": [
      {
        "question": "Is sample waterproof seat cover ready to launch?",
        "answer": "Only publish once supplier details, image rights, price and availability have been checked."
      },
      {
        "question": "How are delivery estimates handled?",
        "answer": "Delivery estimates depend on product availability and customer location."
      }
    ],
    "supplierCostEstimate": 280,
    "supplierNotes": "Imported from supplier-products.csv. Review before adding to live catalogue.",
    "supplierName": "Example Supplier",
    "supplierUrl": "https://example.com"
  }
] satisfies InternalProduct[];
