// Generated by scripts/import-products.mjs. Do not edit manually.
// Add products by adding rows to src/data/product-imports/products.csv.
import type { InternalProduct } from '@/data/products';

export const importedCsvProducts = [
  {
    "slug": "eco-friendly-poop-bags",
    "id": "eco-friendly-poop-bags",
    "name": "Eco-Friendly Poop Bags",
    "price": 89,
    "compareAtPrice": 129,
    "category": "Car Travel",
    "subcategory": "Car Travel",
    "categorySlug": "travel-kits",
    "categoryName": "Car Travel",
    "image": "/products/travel-bowl-set.svg",
    "gallery": [
      "/products/travel-bowl-set.svg",
      "/products/travel-bowl-set.svg"
    ],
    "galleryImages": [
      "/products/travel-bowl-set.svg",
      "/products/travel-bowl-set.svg"
    ],
    "shortDescription": "Eco-friendly poop bags for responsible dog walks",
    "fullDescription": "Biodegradable poop bags that make clean-up easy and environmentally friendly",
    "benefits": [
      "Easy to carry",
      "Biodegradable material",
      "Strong and leak-proof"
    ],
    "features": [
      "eco-friendly",
      "compostable",
      "tear-resistant"
    ],
    "bestFor": [
      "Walks",
      "Parks",
      "Travel"
    ],
    "notIdealFor": [
      "Products without confirmed supplier specifications.",
      "Customers who need guaranteed fit before measurements are checked."
    ],
    "qualityNotes": [
      "Imported product. Confirm specifications, samples and photo permission before setting launchVisible to true.",
      "Check material, packaging and pricing before launch."
    ],
    "material": "Sustainable material",
    "dimensions": [
      "Large roll",
      "Compact pack"
    ],
    "measurements": [
      "Large roll",
      "Compact pack"
    ],
    "compatibility": [
      "Confirm fit against product measurements before ordering."
    ],
    "whatsIncluded": [
      "Eco-Friendly Poop Bags"
    ],
    "howToUse": [
      "Check the product details before first use.",
      "Follow care and safety instructions."
    ],
    "careInstructions": [
      "Clean according to material guidelines.",
      "Store in a dry place when not in use."
    ],
    "deliveryNote": "Delivery estimates depend on product availability and customer location.",
    "returnNote": "Unused items can be returned in line with our returns policy.",
    "seoTitle": "Eco-Friendly Poop Bags South Africa | PawTrip SA",
    "seoDescription": "Shop eco-friendly poop bags in South Africa for responsible dog walks and easy clean-up",
    "tags": [
      "Car Travel",
      "Walks",
      "Parks",
      "Travel"
    ],
    "isBundle": false,
    "relatedProductSlugs": [],
    "sourcePermissionStatus": "original_photos_needed",
    "availability": "in_stock",
    "shippingClass": "standard",
    "imageReady": true,
    "launchVisible": false,
    "problemsSolved": [
      "Easy to carry",
      "Biodegradable material",
      "Strong and leak-proof"
    ],
    "faqs": [
      {
        "question": "Is eco-friendly poop bags suitable for everyday use?",
        "answer": "Yes, it is intended as a practical everyday product."
      },
      {
        "question": "How should I care for it?",
        "answer": "Follow the care instructions and keep it clean and dry between uses."
      }
    ],
    "type": "accessory",
    "longDescription": "Biodegradable poop bags that make clean-up easy and environmentally friendly",
    "included": [
      "Eco-Friendly Poop Bags"
    ],
    "care": [
      "Clean according to material guidelines.",
      "Store in a dry place when not in use."
    ],
    "returnsNote": "Unused items can be returned in line with our returns policy.",
    "keywords": [
      "Car Travel",
      "Walks",
      "Parks",
      "Travel"
    ],
    "supplierCostEstimate": 28,
    "supplierNotes": "Imported from products.csv. Review before publishing.",
    "supplierName": "EcoSupply",
    "supplierUrl": "https://ecosupply.example.com"
  }
] satisfies InternalProduct[];
